package com.synapsecore.integration.dto;

import com.synapsecore.domain.entity.IntegrationConnectorType;
import com.synapsecore.domain.entity.IntegrationImportStatus;
import com.synapsecore.domain.entity.IntegrationSyncMode;
import com.synapsecore.domain.entity.IntegrationTransformationPolicy;
import com.synapsecore.domain.entity.IntegrationValidationPolicy;
import com.synapsecore.integration.IntegrationFailureCode;
import java.time.Instant;

public record IntegrationConnectorResponse(
    Long id,
    String tenantCode,
    String sourceSystem,
    IntegrationConnectorType type,
    String displayName,
    boolean enabled,
    IntegrationSyncMode syncMode,
    Integer syncIntervalMinutes,
    String pullEndpointUrl,
    Instant lastPullAttemptAt,
    Instant lastPullSuccessAt,
    String lastPullStatus,
    String lastPullMessage,
    IntegrationValidationPolicy validationPolicy,
    IntegrationTransformationPolicy transformationPolicy,
    Integer mappingVersion,
    boolean allowDefaultWarehouseFallback,
    String defaultWarehouseCode,
    String notes,
    String supportOwnerActorName,
    String supportOwnerDisplayName,
    boolean inboundAccessConfigured,
    String inboundAccessTokenHint,
    IntegrationConnectorHealthStatus healthStatus,
    String healthSummary,
    Instant lastActivityAt,
    Instant lastSuccessfulActivityAt,
    IntegrationImportStatus lastImportStatus,
    Instant lastImportAt,
    long recentInboundFailureCount,
    long pendingReplayCount,
    long deadLetterCount,
    IntegrationFailureCode lastFailureCode,
    String lastFailureMessage,
    Instant lastFailureAt,
    Instant oldestPendingReplayAt,
    Long oldestPendingReplayAgeSeconds,
    Instant createdAt,
    Instant updatedAt
) {
}
