Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE SYSTEM EXPLAINER"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Services"
Write-Host "--------"
Write-Host "- Frontend: React + Vite single-page application"
Write-Host "- Backend: Spring Boot API, auth/session, realtime, runtime, approvals, replay, integrations"
Write-Host "- Database: PostgreSQL operational record of truth"
Write-Host "- Redis: session store and realtime distributed pub/sub"
Write-Host ""

Write-Host "Local Ports"
Write-Host "-----------"
Write-Host "- Frontend: http://127.0.0.1:5173"
Write-Host "- Backend:  http://127.0.0.1:8080"
Write-Host "- Postgres: localhost:5432"
Write-Host "- Redis:    localhost:6379"
Write-Host ""

Write-Host "Live URLs"
Write-Host "---------"
Write-Host "- Frontend: https://synapscore-frontend-3.onrender.com"
Write-Host "- Backend:  https://synapscore-3.onrender.com"
Write-Host ""

Write-Host "Key Docs"
Write-Host "--------"
Write-Host "- docs\\INDEX.md"
Write-Host "- docs\\system-architecture.md"
Write-Host "- docs\\frontend-flow.md"
Write-Host "- docs\\backend-flow.md"
Write-Host "- docs\\local-runbook.md"
Write-Host "- docs\\render-ops-runbook.md"
Write-Host "- docs\\hosted-proof.md"
Write-Host ""

Write-Host "Common Local Verification"
Write-Host "-------------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-local-connections.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-deployment.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-realtime.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host ""

Write-Host "Hosted Proof"
Write-Host "------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\prepare-hosted-proof.ps1"
Write-Host "- cd frontend"
Write-Host "- npm.cmd run test:e2e:prod"
Write-Host ""

Write-Host "Live Connection Check"
Write-Host "---------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host ""

Write-Host "Common Local Dev Credentials"
Write-Host "----------------------------"
Write-Host "- Workspace: STARTER-OPS"
Write-Host "- Admin: operations.lead / lead-2026"
Write-Host "- Planner: operations.planner / planner-2026"
Write-Host "- Integration: integration.lead / integration-admin-2026"
Write-Host ""

Write-Host "Important Truths"
Write-Host "----------------"
Write-Host "- Demo mode is documented, not a production substitute."
Write-Host "- Hosted proof should only run when backend readiness, auth session, and websocket info are responding."
Write-Host "- If Render frontend is up but backend timeouts persist, treat that as a backend availability issue, not a frontend proof regression."
