Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE PROOF SYSTEM EXPLAINER"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Proof Philosophy"
Write-Host "----------------"
Write-Host "- Proof exists to validate the real deployed frontend and backend together."
Write-Host "- Proof should stop when readiness, auth session, or websocket trust is missing."
Write-Host "- Proof is not a fake demo substitute or a deployment wake-up command."
Write-Host ""

Write-Host "Local Verify Commands"
Write-Host "---------------------"
Write-Host "- cd frontend"
Write-Host "- npm.cmd run verify"
Write-Host "- cd .."
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-local-connections.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-deployment.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-realtime.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host ""

Write-Host "Hosted Proof Commands"
Write-Host "---------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\prepare-hosted-proof.ps1"
Write-Host "- cd frontend"
Write-Host "- npm.cmd run test:e2e:prod"
Write-Host ""

Write-Host "Readiness Expectations"
Write-Host "----------------------"
Write-Host "- frontend live URL responds"
Write-Host "- backend health responds"
Write-Host "- backend liveness responds"
Write-Host "- backend readiness responds"
Write-Host "- auth session endpoint responds"
Write-Host "- websocket info endpoint responds"
Write-Host ""

Write-Host "Proof Blockers"
Write-Host "--------------"
Write-Host "- backend health timeout"
Write-Host "- readiness down or timing out"
Write-Host "- auth session not responding"
Write-Host "- websocket info not responding"
Write-Host "- DB or Redis unavailable"
Write-Host "- proof credentials not loaded"
Write-Host ""

Write-Host "When NOT To Run Proof"
Write-Host "---------------------"
Write-Host "- when frontend is live but backend is timing out"
Write-Host "- when DB/backend are known unavailable"
Write-Host "- when readiness is false"
Write-Host "- when local-only UI work is being mistaken for live validation"
Write-Host ""

Write-Host "Important Docs"
Write-Host "--------------"
Write-Host "- docs\\proof-and-validation.md"
Write-Host "- docs\\hosted-proof.md"
Write-Host "- docs\\technical-reviewer-guide.md"
Write-Host "- docs\\security-and-trust-model.md"
