Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE PILOT READINESS EXPLAINER"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Current Readiness Posture"
Write-Host "-------------------------"
Write-Host "- Frontend UX is productized and verification-backed."
Write-Host "- Backend supports real auth, inventory, orders, replay, scenarios, and runtime flows."
Write-Host "- Hosted proof is part of the discipline, but only when readiness, auth, and websocket trust are healthy."
Write-Host "- Current readiness should be treated as pilot-ready in bounded scope, not as blanket enterprise readiness."
Write-Host ""

Write-Host "What Is Proven"
Write-Host "--------------"
Write-Host "- Tenant workspace experience"
Write-Host "- Productized public and authenticated frontend"
Write-Host "- Catalog, inventory, orders, alerts, recommendations, integrations"
Write-Host "- Replay and recovery model"
Write-Host "- Scenario approval and execution flow"
Write-Host "- Runtime trust and degraded-state UX"
Write-Host "- Frontend verify discipline and hosted proof gating philosophy"
Write-Host ""

Write-Host "What Is Pilot-Ready"
Write-Host "-------------------"
Write-Host "- One bounded operational lane"
Write-Host "- Real operator onboarding"
Write-Host "- Narrow connector scope"
Write-Host "- Replay and scenario validation"
Write-Host "- Runtime and incident observation"
Write-Host ""

Write-Host "What Still Needs Hardening"
Write-Host "--------------------------"
Write-Host "- Broader enterprise identity posture"
Write-Host "- Wider connector breadth"
Write-Host "- Larger-scale infrastructure resilience"
Write-Host "- Deeper observability and metrics maturity"
Write-Host "- More mature high-availability and scale posture"
Write-Host ""

Write-Host "Proof Philosophy"
Write-Host "----------------"
Write-Host "- Proof exists to validate truth, not to create fake confidence."
Write-Host "- Hosted proof should pause when backend readiness, auth, or websocket trust is unhealthy."
Write-Host "- Local verification and hosted proof work together rather than replace each other."
Write-Host ""

Write-Host "Safe Adoption Guidance"
Write-Host "----------------------"
Write-Host "- Start with one company workspace."
Write-Host "- Onboard a small set of real roles."
Write-Host "- Choose one meaningful connector lane."
Write-Host "- Validate replay and approvals deliberately."
Write-Host "- Expand only after the first lane is stable."
Write-Host ""

Write-Host "Important Docs"
Write-Host "--------------"
Write-Host "- docs\\buyer-due-diligence-guide.md"
Write-Host "- docs\\pilot-adoption-roadmap.md"
Write-Host "- docs\\enterprise-evaluation-checklist.md"
Write-Host "- docs\\platform-differentiation.md"
Write-Host "- docs\\operational-value-guide.md"
Write-Host "- docs\\pilot-faq.md"
