Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE EXPLAINER SUITE"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""
Write-Host "Use these scripts when you want the product explained in separated lanes."
Write-Host ""
Write-Host "1. Product"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-product.ps1"
Write-Host "   What SynapseCore is, what it does, and the full operating promise."
Write-Host ""
Write-Host "2. Architecture"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-architecture.ps1"
Write-Host "   How the platform is built across backend, frontend, realtime, and trust."
Write-Host ""
Write-Host "3. Connections"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-connections.ps1"
Write-Host "   How company systems connect into SynapseCore and what each inbound lane does."
Write-Host ""
Write-Host "4. Usage"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-usage.ps1"
Write-Host "   How a company team signs in, works, approves, recovers, and runs the platform daily."
Write-Host ""
Write-Host "5. API"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-api.ps1"
Write-Host "   Full backend surface by domain: orders, fulfillment, integrations, control, auth, and trust."
Write-Host ""
Write-Host "6. Pages"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-pages.ps1"
Write-Host "   Full product page map, route by route, and what each page is for."
Write-Host ""
Write-Host "7. Onboarding"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-onboarding.ps1"
Write-Host "   How a company is onboarded, configured, and brought into live use."
Write-Host ""
Write-Host "8. Testing"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-testing.ps1"
Write-Host "   What to verify, which scripts prove what, and what ready really means."
Write-Host ""
Write-Host "9. Deployment And Operations"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-deployment-operations.ps1"
Write-Host "   How to prepare envs, deploy, verify, back up, restore, and operate safely."
Write-Host ""
Write-Host "10. Company Fit"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts\explain-company-fit.ps1"
Write-Host "   Which companies SynapseCore fits, what value it gives them, and what changes operationally."
Write-Host ""
Write-Host "11. Existing Guided Repo Tour"
Write-Host "   bash scripts/explain-project.sh"
Write-Host "   Repo-first walkthrough of folders, packages, and the original MVP identity."
