Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE INFRASTRUCTURE EXPLAINER"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Service Map"
Write-Host "-----------"
Write-Host "- Frontend SPA -> public pages + authenticated command center"
Write-Host "- Backend API -> auth, catalog, inventory, orders, replay, scenarios, runtime"
Write-Host "- PostgreSQL -> operational record of truth"
Write-Host "- Redis -> session storage + realtime pub/sub"
Write-Host "- Realtime -> SockJS/STOMP tenant-scoped live updates"
Write-Host ""

Write-Host "Local URLs"
Write-Host "----------"
Write-Host "- Frontend: http://127.0.0.1:5173"
Write-Host "- Backend:  http://127.0.0.1:8080"
Write-Host "- Health:   http://127.0.0.1:8080/actuator/health"
Write-Host "- WS Info:  http://127.0.0.1:8080/ws/info"
Write-Host ""

Write-Host "Live URLs"
Write-Host "---------"
Write-Host "- Frontend: https://synapscore-frontend-3.onrender.com"
Write-Host "- Backend:  https://synapscore-3.onrender.com"
Write-Host "- Readiness: https://synapscore-3.onrender.com/actuator/health/readiness"
Write-Host "- Liveness:  https://synapscore-3.onrender.com/actuator/health/liveness"
Write-Host ""

Write-Host "Communication Chain"
Write-Host "-------------------"
Write-Host "1. Browser loads frontend shell"
Write-Host "2. Frontend fetches backend APIs through VITE_API_URL"
Write-Host "3. Frontend opens realtime connection through VITE_WS_URL (/ws)"
Write-Host "4. Backend reads/writes PostgreSQL"
Write-Host "5. Backend uses Redis for session + distributed realtime posture"
Write-Host "6. Backend publishes tenant-scoped operational updates"
Write-Host "7. UI updates command-center surfaces without full refresh"
Write-Host ""

Write-Host "Important Docs"
Write-Host "--------------"
Write-Host "- docs\\infrastructure-handbook.md"
Write-Host "- docs\\system-architecture.md"
Write-Host "- docs\\infrastructure-communication-map.md"
Write-Host "- docs\\backend-flow.md"
Write-Host "- docs\\frontend-flow.md"
Write-Host "- docs\\data-flow-playbook.md"
Write-Host "- docs\\render-ops-runbook.md"
Write-Host "- docs\\engineering-review.md"
Write-Host "- docs\\operations-handbook.md"
Write-Host "- docs\\quality-gates.md"
Write-Host ""

Write-Host "Proof Command Path"
Write-Host "------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\engineering-readiness.ps1"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\prepare-hosted-proof.ps1"
Write-Host "- cd frontend"
Write-Host "- npm.cmd run test:e2e:prod"
Write-Host ""

Write-Host "Current Status Assumptions"
Write-Host "--------------------------"
Write-Host "- Frontend can be live while backend is unavailable."
Write-Host "- Backend readiness must pass before hosted proof runs."
Write-Host "- DB or Redis failure can block readiness and auth/ws flows."
Write-Host "- Demo mode docs do not replace real backend validation."
