Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE PROJECT MAP"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Major Repository Sections"
Write-Host "-------------------------"
Write-Host "- backend      -> Spring Boot domain, auth, replay, scenarios, runtime"
Write-Host "- frontend     -> React public site and authenticated command center"
Write-Host "- infrastructure -> Docker Compose, env templates, edge/deployment support"
Write-Host "- docs         -> architecture, product, proof, recovery, roadmap, buyer docs"
Write-Host "- scripts      -> checks, explainers, proof prep, verification, recovery helpers"
Write-Host ""

Write-Host "Major Docs"
Write-Host "----------"
Write-Host "- docs\\master-project-tree.md"
Write-Host "- docs\\system-communication-map.md"
Write-Host "- docs\\master-product-roadmap.md"
Write-Host "- docs\\engineering-priorities.md"
Write-Host "- docs\\infrastructure-evolution-roadmap.md"
Write-Host "- docs\\proof-system-evolution.md"
Write-Host "- docs\\contributor-guide.md"
Write-Host ""

Write-Host "Frontend / Backend Paths"
Write-Host "------------------------"
Write-Host "- frontend\\src"
Write-Host "- frontend\\tests"
Write-Host "- backend\\src\\main\\java\\com\\synapsecore"
Write-Host "- backend\\src\\main\\resources"
Write-Host "- backend\\src\\test\\java\\com\\synapsecore"
Write-Host ""

Write-Host "Infrastructure Paths"
Write-Host "--------------------"
Write-Host "- infrastructure\\docker-compose.yml"
Write-Host "- infrastructure\\docker-compose.prod.yml"
Write-Host "- infrastructure\\env"
Write-Host "- render.yaml"
Write-Host ""

Write-Host "Proof Commands"
Write-Host "--------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\prepare-hosted-proof.ps1"
Write-Host "- cd frontend"
Write-Host "- npm.cmd run test:e2e:prod"
Write-Host ""

Write-Host "Operational Scripts"
Write-Host "-------------------"
Write-Host "- scripts\\check-local-connections.ps1"
Write-Host "- scripts\\check-live-connections.ps1"
Write-Host "- scripts\\explain-infrastructure.ps1"
Write-Host "- scripts\\explain-proof-system.ps1"
Write-Host "- scripts\\recovery-checklist.ps1"
Write-Host "- scripts\\verify-deployment.ps1"
Write-Host "- scripts\\verify-realtime.ps1"
Write-Host ""

Write-Host "Roadmap Docs"
Write-Host "------------"
Write-Host "- docs\\master-product-roadmap.md"
Write-Host "- docs\\infrastructure-evolution-roadmap.md"
Write-Host "- docs\\enterprise-hardening-roadmap.md"
Write-Host "- docs\\current-limitations.md"
Write-Host ""

Write-Host "Guidance"
Write-Host "--------"
Write-Host "- Treat frontend, backend, proof, and runtime trust as one coordinated system."
Write-Host "- Do not run hosted proof while readiness, auth, or websocket trust is unhealthy."
Write-Host "- Use docs\\INDEX.md as the primary navigation page for the repository."
