Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot

Write-Host "=================================================="
Write-Host "SYNAPSECORE RECOVERY CHECKLIST"
Write-Host "=================================================="
Write-Host "Repo root: $rootDir"
Write-Host ""

Write-Host "Recovery Sequence"
Write-Host "-----------------"
Write-Host "1. Classify frontend and backend separately."
Write-Host "2. Check health, readiness, auth session, and websocket info."
Write-Host "3. Confirm DB and Redis dependency posture."
Write-Host "4. Restore infrastructure or backend availability."
Write-Host "5. Rerun live/local checks."
Write-Host "6. Only then resume proof preparation and hosted proof."
Write-Host ""

Write-Host "Live Check Commands"
Write-Host "-------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-frontend-3.onrender.com"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-3.onrender.com/actuator/health"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-3.onrender.com/actuator/health/readiness"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-3.onrender.com/actuator/health/liveness"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-3.onrender.com/api/auth/session"
Write-Host "- curl.exe -i --max-time 20 https://synapscore-3.onrender.com/ws/info"
Write-Host ""

Write-Host "Local Check Commands"
Write-Host "--------------------"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\check-local-connections.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-deployment.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host "- powershell -ExecutionPolicy Bypass -File scripts\\verify-realtime.ps1 -FrontendUrl http://127.0.0.1:5173 -BackendUrl http://127.0.0.1:8080"
Write-Host ""

Write-Host "Readiness / Auth / WS Endpoints"
Write-Host "-------------------------------"
Write-Host "- /actuator/health"
Write-Host "- /actuator/health/readiness"
Write-Host "- /actuator/health/liveness"
Write-Host "- /api/auth/session"
Write-Host "- /ws/info"
Write-Host ""

Write-Host "Proof Rerun Order"
Write-Host "-----------------"
Write-Host "1. powershell -ExecutionPolicy Bypass -File scripts\\check-live-connections.ps1"
Write-Host "2. powershell -ExecutionPolicy Bypass -File scripts\\prepare-hosted-proof.ps1"
Write-Host "3. cd frontend"
Write-Host "4. npm.cmd run test:e2e:prod"
Write-Host ""

Write-Host "When NOT To Run Hosted Proof"
Write-Host "----------------------------"
Write-Host "- when backend health times out"
Write-Host "- when readiness is false or timing out"
Write-Host "- when auth session does not respond"
Write-Host "- when websocket info does not respond"
Write-Host "- when DB or Redis are known unavailable"
Write-Host "- when frontend-only work is being mistaken for live validation"
Write-Host ""

Write-Host "Dependency Reminders"
Write-Host "--------------------"
Write-Host "- PostgreSQL is part of readiness and operational truth."
Write-Host "- Redis is part of current production session and realtime posture."
Write-Host "- A live frontend shell does not prove backend trust."
Write-Host "- Hosted proof is a validation step, not a recovery probe."
